statistics:
- platform: statistics
  name: House Battery Load 30 mins
  unique_id: house_battery_load_30_mins
  entity_id: sensor.opti_battery_power_w
  state_characteristic: mean
  max_age:
    minutes: 30
  sampling_size: 360
  precision: 0
- platform: statistics
  name: Haus Stromverbrauch 60 min
  unique_id: haus_stromverbrauch_60_min
  entity_id: sensor.opti_house_consumption_w
  state_characteristic: mean
  max_age:
    minutes: 60
  sampling_size: 360
  precision: 0
- platform: statistics
  name: Opti House Consumption 60min W
  unique_id: opti_house_consumption_60min_w
  entity_id: sensor.opti_house_consumption_w
  state_characteristic: mean
  max_age:
    minutes: 60
  sampling_size: 1500
  precision: 0
