"""Entity settings derived from the MIT licensed Opti helper contract."""

NUMBER_DEFINITIONS = {'input_number.akkusteuerung_ladestaerke_soll': {'name': 'Akkusteuerung Ladestärke Soll',
                                                 'min': 100,
                                                 'max': 10000,
                                                 'step': 100,
                                                 'unit_of_measurement': 'W',
                                                 'mode': 'box',
                                                 'icon': 'mdi:battery-arrow-up',
                                                 'default': 2000},
 'input_number.akkusteuerung_min_ladestaerke': {'name': 'Akkusteuerung Min Ladestärke',
                                                'min': 0,
                                                'max': 2000,
                                                'step': 50,
                                                'unit_of_measurement': 'W',
                                                'mode': 'box',
                                                'default': 0},
 'input_number.akkusteuerung_max_ladestaerke': {'name': 'Akkusteuerung Max Ladestärke',
                                                'min': 0,
                                                'max': 10000,
                                                'step': 1,
                                                'unit_of_measurement': 'W',
                                                'mode': 'box',
                                                'default': 3000},
 'input_number.akkusteuerung_entladestaerke_soll': {'name': 'Akkusteuerung Entladestärke Soll',
                                                    'min': 100,
                                                    'max': 10000,
                                                    'step': 100,
                                                    'unit_of_measurement': 'W',
                                                    'mode': 'box',
                                                    'icon': 'mdi:battery-arrow-down',
                                                    'default': 2000},
 'input_number.akkusteuerung_min_entladestaerke': {'name': 'Akkusteuerung Min Entladestärke',
                                                   'min': 0,
                                                   'max': 2000,
                                                   'step': 50,
                                                   'unit_of_measurement': 'W',
                                                   'mode': 'box',
                                                   'default': 0},
 'input_number.akkusteuerung_max_entladestaerke': {'name': 'Akkusteuerung Max Entladestärke',
                                                   'min': 0,
                                                   'max': 10000,
                                                   'step': 1,
                                                   'unit_of_measurement': 'W',
                                                   'mode': 'box',
                                                   'default': 5000},
 'input_number.akkusteuerung_wr_ac_ueberschuss_grenze': {'name': 'Akkusteuerung AC-Überschuss '
                                                                 'Grenze',
                                                         'min': 0,
                                                         'max': 15000,
                                                         'step': 100,
                                                         'unit_of_measurement': 'W',
                                                         'mode': 'box',
                                                         'icon': 'mdi:transmission-tower-export',
                                                         'default': 0},
 'input_number.akkusteuerung_wr_70proz_ueberschuss_grenze': {'name': 'Akkusteuerung 70%-Überschuss '
                                                                     'Grenze',
                                                             'min': 0,
                                                             'max': 25000,
                                                             'step': 100,
                                                             'unit_of_measurement': 'W',
                                                             'mode': 'box',
                                                             'default': 0},
 'input_number.akkusteuerung_ueberschuss_veto_grenze': {'name': 'Akkusteuerung Überschuss-Veto '
                                                                'Grenze',
                                                        'min': 200,
                                                        'max': 5000,
                                                        'step': 50,
                                                        'unit_of_measurement': 'W',
                                                        'mode': 'box',
                                                        'icon': 'mdi:transmission-tower-export',
                                                        'default': 500},
 'input_number.akkusteuerung_ueberschuss_veto_aus_grenze': {'name': 'Akkusteuerung Überschuss-Veto '
                                                                    'Aus-Grenze',
                                                            'min': 100,
                                                            'max': 5000,
                                                            'step': 50,
                                                            'unit_of_measurement': 'W',
                                                            'mode': 'box',
                                                            'icon': 'mdi:transmission-tower-export',
                                                            'default': 250},
 'input_number.akkusteuerung_ueberschuss_veto_knappheit_faktor': {'name': 'Akkusteuerung '
                                                                          'Überschuss-Veto '
                                                                          'Knappheits-Faktor',
                                                                  'min': 1,
                                                                  'max': 10,
                                                                  'step': 0.5,
                                                                  'mode': 'box',
                                                                  'icon': 'mdi:scale-balance',
                                                                  'default': 1},
 'input_number.minsoc': {'name': 'Akku Min SoC',
                         'min': 0,
                         'max': 100,
                         'step': 1,
                         'unit_of_measurement': '%',
                         'mode': 'slider',
                         'icon': 'mdi:battery-low',
                         'default': 10},
 'input_number.maxsoc': {'name': 'Akku Max SoC',
                         'min': 0,
                         'max': 100,
                         'step': 1,
                         'unit_of_measurement': '%',
                         'mode': 'slider',
                         'icon': 'mdi:battery-high',
                         'default': 95},
 'input_number.ladepreis': {'name': 'Akku Ladepreis (Referenz)',
                            'min': -1,
                            'max': 1,
                            'step': 0.001,
                            'unit_of_measurement': 'EUR/kWh',
                            'mode': 'box',
                            'icon': 'mdi:currency-eur',
                            'default': -1},
 'input_number.mindestpreisdifferenz_lade_entladepreis': {'name': 'Mindestpreisdifferenz '
                                                                  'Laden/Entladen',
                                                          'min': 0,
                                                          'max': 0.3,
                                                          'step': 0.005,
                                                          'unit_of_measurement': 'EUR/kWh',
                                                          'mode': 'box',
                                                          'icon': 'mdi:cash-plus',
                                                          'default': 0.08},
 'input_number.opti_peak_verbrauch_kw': {'name': 'Opti Peak-Verbrauch',
                                         'min': 0.1,
                                         'max': 5,
                                         'step': 0.1,
                                         'unit_of_measurement': 'kW',
                                         'mode': 'box',
                                         'icon': 'mdi:home-lightning-bolt',
                                         'default': 0.8},
 'input_number.opti_einspeiseverguetung_ct': {'name': 'Opti Einspeiseverguetung',
                                              'min': 0,
                                              'max': 30,
                                              'step': 0.1,
                                              'unit_of_measurement': 'ct/kWh',
                                              'mode': 'box',
                                              'icon': 'mdi:solar-power-variant',
                                              'default': 0},
 'input_number.opti_netzlade_spread_ct': {'name': 'Opti Netzlade-Spread',
                                          'min': 0,
                                          'max': 100,
                                          'step': 0.5,
                                          'unit_of_measurement': 'ct/kWh',
                                          'mode': 'box',
                                          'icon': 'mdi:swap-vertical-bold',
                                          'default': 10},
 'input_number.opti_peak_min_aufschlag_ct': {'name': 'Opti Peak Mindestaufschlag',
                                             'min': 0,
                                             'max': 100,
                                             'step': 0.5,
                                             'unit_of_measurement': 'ct/kWh',
                                             'mode': 'box',
                                             'icon': 'mdi:filter-outline',
                                             'default': 5},
 'input_number.opti_forecast_optimismus': {'name': 'Opti Forecast-Optimismus',
                                           'min': 0,
                                           'max': 100,
                                           'step': 5,
                                           'unit_of_measurement': '%',
                                           'mode': 'slider',
                                           'icon': 'mdi:weather-sunny',
                                           'default': 0},
 'input_number.opti_halte_spread_ct': {'name': 'Opti Halte-Spread',
                                       'min': 0,
                                       'max': 50,
                                       'step': 0.5,
                                       'unit_of_measurement': 'ct/kWh',
                                       'mode': 'box',
                                       'icon': 'mdi:hand-back-right-outline',
                                       'default': 5},
 'input_number.opti_balancing_intervall_tage': {'name': 'Opti Balancing Intervall',
                                                'min': 0,
                                                'max': 60,
                                                'step': 1,
                                                'unit_of_measurement': 'Tage',
                                                'mode': 'box',
                                                'icon': 'mdi:calendar-refresh',
                                                'default': 0},
 'input_number.opti_balancing_karenz_tage': {'name': 'Opti Balancing Karenz',
                                             'min': 0,
                                             'max': 14,
                                             'step': 1,
                                             'unit_of_measurement': 'Tage',
                                             'mode': 'box',
                                             'icon': 'mdi:timer-sand',
                                             'default': 3},
 'input_number.opti_balancing_max_ct': {'name': 'Opti Balancing Preisdeckel',
                                        'min': 0,
                                        'max': 50,
                                        'step': 0.5,
                                        'unit_of_measurement': 'ct/kWh',
                                        'mode': 'box',
                                        'icon': 'mdi:cash-lock',
                                        'default': 0},
 'input_number.opti_balancing_done_soc': {'name': 'Opti Balancing Done-SoC',
                                          'initial': 98.5,
                                          'min': 90,
                                          'max': 100,
                                          'step': 0.5,
                                          'unit_of_measurement': '%',
                                          'mode': 'box',
                                          'icon': 'mdi:battery-heart-variant',
                                          'default': 98.5},
 'input_number.opti_balancing_spreizungs_schwelle': {'name': 'Opti Balancing Spreizungs-Schwelle',
                                                     'min': 0,
                                                     'max': 49,
                                                     'step': 1,
                                                     'unit_of_measurement': 'mV',
                                                     'mode': 'box',
                                                     'icon': 'mdi:arrow-collapse-vertical',
                                                     'default': 0},
 'input_number.opti_balancing_bedarf_cooldown_tage': {'name': 'Opti Balancing Bedarf-Cooldown Tage',
                                                      'min': 0,
                                                      'max': 30,
                                                      'step': 1,
                                                      'unit_of_measurement': 'Tage',
                                                      'mode': 'box',
                                                      'icon': 'mdi:timer-sand',
                                                      'default': 5}}

SWITCH_DEFINITIONS = {'input_boolean.akku_opti_automatik': {'name': 'Akku Opti-Automatik',
                                       'icon': 'mdi:battery-sync',
                                       'default': False},
 'input_boolean.hausakku_aus_netz_laden': {'name': 'Hausakku aus Netz laden',
                                           'icon': 'mdi:transmission-tower',
                                           'default': False},
 'input_boolean.opti_prognose_netzladen': {'name': 'Reserveplanung mit Netzladen erlauben',
                                           'icon': 'mdi:transmission-tower',
                                           'default': False},
 'input_boolean.opti_pv_ueberschuss_ladung': {'name': 'Opti PV-Überschussladung erlauben',
                                              'icon': 'mdi:solar-power',
                                              'default': True},
 'input_boolean.opti_ev_akku_pause': {'name': 'Opti EV-Entladesperre',
                                      'icon': 'mdi:car-electric',
                                      'default': False},
 'input_boolean.opti_balancing_netzladen': {'name': 'Opti Balancing darf ans Netz',
                                            'icon': 'mdi:battery-heart-variant',
                                            'default': False}}
